# Gitleaks configuration file

# Title for the configuration
title = "Gitleaks Configuration"

# A description for the configuration
description = "Fintech DevSecOps gitleaks configuration to detect secrets and credentials"

# First, allow list some benign paths/files
[[allowlist]]
description = "Allowlisted files"
paths = [
    '''(.*?)(spec|test|mock|example|sample)(.*)\.(.*)$''',
    '''(.*?)docs(.*)''',
]

# Allowlisted regexes - stuff we know is safe
[[allowlist]]
description = "Allowlisted patterns"
regexes = [
    '''EXAMPLE.*KEY''',
    '''fake.*key''',
    '''dummy.*key''',
]

# Rules for detecting secrets

# AWS
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
secretGroup = 1
entropy = 3.5
keywords = [
    "AKIA",
    "aws_access_key",
    "aws_key",
    "aws_secret",
]

# Generic API key
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[._-]?key|token|api|apikey|auth)[a-z0-9_ .\-,]{0,25}[:=>]{1,2}[[:blank:]]*["']?([a-z0-9]{20,})["']?'''
secretGroup = 2
entropy = 3.5
keywords = [
    "api_key",
    "apikey",
    "authorization",
]

# GitHub token
[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''(ghp_[a-zA-Z0-9]{36})|(ghs_[a-zA-Z0-9]{36})|(github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59})'''
secretGroup = 1
keywords = [
    "github",
    "token",
    "github_token",
    "GITHUB_TOKEN",
]

# JWT token
[[rules]]
id = "jwt"
description = "JSON Web Token"
regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''
secretGroup = 0
keywords = [
    "json web token",
    "jwt",
]

# Password in code
[[rules]]
id = "password-in-code"
description = "Password in code"
regex = '''(?i)(password|passwd|pwd|secret)[a-z0-9_ .\-,]{0,25}[:=>]{1,2}[[:blank:]]*["']([^"']{4,})["']'''
secretGroup = 2
keywords = [
    "password",
    "passwd",
    "pwd",
    "secret",
] 