apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/refresh: "normal"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/fintech-organization/infrastructure.git
    targetRevision: HEAD
    path: kubernetes/security
    kustomize:
      images:
        - name: opa
          newTag: 0.42.0
      commonAnnotations:
        securityContext: restricted
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/failurePolicy
  info:
    - name: Ownership
      value: "Security Team"
    - name: Compliance
      value: "PCI-DSS, ISO27001" 