name: Security Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite

jobs:
  secret-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Detect secrets in code
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        with:
          config-path: .github/gitleaks.toml

  sast-scan:
    name: SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit --audit-level=high
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  iac-security:
    name: IaC Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          soft_fail: true
      
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@master
        with:
          format: sarif
          soft_fail: true

  container-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    needs: [secret-scan, sast-scan, dependency-check, iac-security]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: fintech-app:${{ github.sha }}
          load: true
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fintech-app:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

  security-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    needs: [secret-scan, sast-scan, dependency-check, iac-security, container-scan]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      
      - name: Combine security reports
        run: |
          mkdir -p security-reports
          find . -name "*.sarif" -o -name "*.json" | xargs -I{} cp {} security-reports/
          echo "Security scan completed at $(date)" > security-reports/summary.txt
      
      - name: Archive security reports
        uses: actions/upload-artifact@v2
        with:
          name: security-reports
          path: security-reports/

  notify:
    name: Notify Security Team
    runs-on: ubuntu-latest
    needs: security-report
    if: failure()
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "danger",
                  "title": "Security Scan Failed ⚠️",
                  "text": "One or more security checks failed in the ${{ github.workflow }} workflow. Please check the security reports.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/favicon.ico"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 